global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'garmin-exporter'
    static_configs:
      - targets: ['host.docker.internal:5051']
        labels:
          environment: 'development'
          service: 'garmin-exporter-api'
  - job_name: 'auth-exporter'
    static_configs:
      - targets: ['host.docker.internal:5052']
        labels:
          environment: 'development'
          service: 'auth-exporter-api'